FROM node:14 AS builder

WORKDIR /app

COPY ./front-lib-react/package*.json ./
RUN npm install

COPY ./front-lib-react/ .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
