FROM maven:3.9.9-amazoncorretto-17 AS builder

WORKDIR /app

COPY ./dynamoDbClient/pom.xml .
COPY ./dynamoDbClient/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
